/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-05-20 04:08:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import service.ProductService;
import model.Product;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import model.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1747559456874L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1747660341753L));
    _jspx_dependants.put("jar:file:/C:/Users/User/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1747660548302L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("model.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("service.ProductService");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("java.util.stream.Collectors");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Get all products and group them by category
    ProductService productService = new ProductService();
    List<Product> allProducts = productService.getAllProducts();

    // Get featured products (limit to 5)
    List<Product> featuredProducts = allProducts.stream()
            .limit(5)
            .collect(Collectors.toList());

    // Group products by category
    Map<String, List<Product>> productsByCategory = allProducts.stream()
            .collect(Collectors.groupingBy(Product::getCategory));

    // Get all categories
    List<String> categories = productService.getAllCategories();

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>OnlineMediCare - Home</title>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/webjars/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/tailwindcss\">\r\n");
      out.write("        .my-gradiant{\r\n");
      out.write("            @apply bg-gradient-to-b from-green-900 to-green-300 bg-gradient-to-r from-green-700 to-green-500\r\n");
      out.write("        }\r\n");
      out.write("        .menu-items{\r\n");
      out.write("            @apply rounded py-[5px] px-[5px] my-[8px] hover:bg-gray-100 transition delay-10 duration-600 ease-in-out cursor-pointer\r\n");
      out.write("        }\r\n");
      out.write("        .gray-border{\r\n");
      out.write("            @apply border-t-[8px] border-blue-100 py-6\r\n");
      out.write("        }\r\n");
      out.write("        .product-categories-items-li{\r\n");
      out.write("            @apply rounded shadow-md hover:shadow-lg transition-shadow hover:-translate-y-1 hover:scale-105 p-[10px]\r\n");
      out.write("        }\r\n");
      out.write("        .product-main{\r\n");
      out.write("            @apply bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow hover:-translate-y-1 hover:scale-105\r\n");
      out.write("        }\r\n");
      out.write("        .product-image{\r\n");
      out.write("            @apply w-full h-48 object-contain p-4\r\n");
      out.write("        }\r\n");
      out.write("        .product-button{\r\n");
      out.write("            @apply w-full bg-green-600 hover:-translate-y-1 hover:scale-105 hover:bg-green-700 text-white py-2 rounded-md mt-3 transition-colors transition delay-150 duration-300 ease-in-out\r\n");
      out.write("        }\r\n");
      out.write("        .product-title{\r\n");
      out.write("            @apply font-semibold text-lg mb-1\r\n");
      out.write("        }\r\n");
      out.write("        .product-price{\r\n");
      out.write("            @apply text-green-600 font-bold text-xl\r\n");
      out.write("        }\r\n");
      out.write("        .product-container{\r\n");
      out.write("            @apply grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6 px-8\r\n");
      out.write("        }\r\n");
      out.write("        .product-container-title{\r\n");
      out.write("            @apply text-3xl font-bold text-center mb-4\r\n");
      out.write("        }\r\n");
      out.write("        .product-container-title-div{\r\n");
      out.write("            @apply container mx-auto px-4 py-8 flex flex-col\r\n");
      out.write("        }\r\n");
      out.write("        .section-main-div{\r\n");
      out.write("            @apply mx-[2rem]\r\n");
      out.write("        }\r\n");
      out.write("        .product-container-main-div{\r\n");
      out.write("            @apply flex flex-col gap-6\r\n");
      out.write("        }\r\n");
      out.write("        .section-highlight {\r\n");
      out.write("            @apply transition-all duration-500 transform scale-105;\r\n");
      out.write("        }\r\n");
      out.write("        .toast {\r\n");
      out.write("            @apply fixed top-20 right-5 bg-green-600 text-white py-2 px-4 rounded-md shadow-lg z-50 transition-all duration-300 transform translate-x-full;\r\n");
      out.write("        }\r\n");
      out.write("        .toast-show {\r\n");
      out.write("            @apply translate-x-0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Toast notification for add to cart -->\r\n");
      out.write("<div id=\"toast\" class=\"toast\">\r\n");
      out.write("    <div class=\"flex items-center\">\r\n");
      out.write("        <i class=\"fas fa-check-circle mr-2\"></i>\r\n");
      out.write("        <span id=\"toast-message\">Item added to cart!</span>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--hero section-->\r\n");
      out.write("<div class=\"bg-[url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/storebackground.jpg')] h-[95vh] w-full bg-cover bg-center relative\">\r\n");
      out.write("    <!--navbar-->\r\n");
      out.write("    <header class=\"fixed top-0 left-0 right-0 z-50 w-full \">\r\n");
      out.write("        <div class=\"flex py-[6px] px-[50px] justify-between items-center w-full my-gradiant\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-[#ffff] text-3xl bg-green-700 py-[10px] px-[15px] rounded-full\">MEDICARE CENTER</a>\r\n");
      out.write("            <!--search bar-->\r\n");
      out.write("            <div class=\"flex gap-2 bg-white py-[5px] px-[15px] rounded-[20px] border w-full max-w-3xl items-center \" >\r\n");
      out.write("                <input type=\"search\" placeholder=\"Search medicines...\" class=\"grow focus:outline-none text-sm\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-solid fa-magnifying-glass text-xl\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Second header bar -->\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');

  User headerUser = (User) session.getAttribute("user");
  boolean isLoggedIn = headerUser != null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"flex pl-[50px] pr-[30px] bg-blue-100 items-center justify-between h-[70px]\">\r\n");
      out.write("  <!-- Logo and Navigation Menu -->\r\n");
      out.write("  <ul class=\"flex justify-center gap-5 items-center\">\r\n");
      out.write("    <button id=\"menu-btn\" class=\"md:hidden\">\r\n");
      out.write("      <i class=\"fa-solid fa-bars text-xl my-[12px] cursor-pointer hover:scale-110\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <!-- Desktop Menu -->\r\n");
      out.write("    <div class=\"hidden md:flex justify-center gap-5\">\r\n");
      out.write("      <li class=\"menu-items\"><a href=\"index.jsp\">HOME</a></li>\r\n");
      out.write("      <li class=\"menu-items\"><a href=\"#categories\" class=\"smooth-scroll\">SHOP</a></li>\r\n");
      out.write("      <li class=\"menu-items\"><a href=\"#about\" class=\"smooth-scroll\">About Us</a></li>\r\n");
      out.write("      <li class=\"menu-items\"><a href=\"#\">Contact us</a></li>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Menu -->\r\n");
      out.write("    <div id=\"mobile-menu\" class=\"hidden md:hidden absolute top-16 left-0 w-full bg-white shadow-lg z-50 rounded-b-lg\">\r\n");
      out.write("      <li class=\"menu-items px-6\"><a href=\"index.jsp\">HOME</a></li>\r\n");
      out.write("      <li class=\"menu-items px-6\"><a href=\"#categories\">SHOP</a></li>\r\n");
      out.write("      <li class=\"menu-items px-6\"><a href=\"#about\">About Us</a></li>\r\n");
      out.write("      <li class=\"menu-items px-6\"><a href=\"#\">Contact us</a></li>\r\n");
      out.write("\r\n");
      out.write("      <!-- Mobile-only login/register or user menu -->\r\n");
      out.write("      ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("      <li class=\"menu-items px-6 border-t border-gray-200 mt-2 pt-2\">\r\n");
      out.write("        <a href=\"dashboard.jsp\" class=\"flex items-center\">\r\n");
      out.write("          <i class=\"fas fa-user-circle mr-2\"></i> My Dashboard\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"menu-items px-6\">\r\n");
      out.write("        <a href=\"logout.jsp\" class=\"flex items-center text-red-500\">\r\n");
      out.write("          <i class=\"fas fa-sign-out-alt mr-2\"></i> Logout\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      ");
 } else { 
      out.write("\r\n");
      out.write("      <li class=\"menu-items px-6 border-t border-gray-200 mt-2 pt-2\">\r\n");
      out.write("        <a href=\"login.jsp\" class=\"flex items-center\">\r\n");
      out.write("          <i class=\"fas fa-sign-in-alt mr-2\"></i> User Login\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"menu-items px-6\">\r\n");
      out.write("        <a href=\"admin-login.jsp\" class=\"flex items-center\">\r\n");
      out.write("          <i class=\"fas fa-user-shield mr-2\"></i> Admin Login\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"menu-items px-6\">\r\n");
      out.write("        <a href=\"register.jsp\" class=\"flex items-center\">\r\n");
      out.write("          <i class=\"fas fa-user-plus mr-2\"></i> Register\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      // Get DOM elements\r\n");
      out.write("      const menuBtn = document.getElementById('menu-btn');\r\n");
      out.write("      const mobileMenu = document.getElementById('mobile-menu');\r\n");
      out.write("\r\n");
      out.write("      // Toggle mobile menu\r\n");
      out.write("      menuBtn.addEventListener('click', () => {\r\n");
      out.write("        mobileMenu.classList.toggle('hidden');\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Close mobile menu when clicking outside\r\n");
      out.write("      document.addEventListener('click', (event) => {\r\n");
      out.write("        if (!mobileMenu.contains(event.target) && event.target !== menuBtn) {\r\n");
      out.write("          mobileMenu.classList.add('hidden');\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("  <!-- Right side menu (Cart, User Profile) -->\r\n");
      out.write("  <ul class=\"flex gap-4 items-center\">\r\n");
      out.write("    <li class=\"bg-green-500 my-[10px] px-[8px] py-[6px] text-black rounded-[5px] text-sm hover:bg-green-600 hover:text-white transition delay-10 duration-600 ease-in-out cursor-pointer\">\r\n");
      out.write("      <a href=\"prescriptionUpload.jsp\">Upload Your Prescription</a>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\" class=\"p-3 hover:scale-110 relative\">\r\n");
      out.write("      <i class=\"fas fa-shopping-cart text-xl\"></i>\r\n");
      out.write("      <span class=\"absolute -top-1 -right-1 bg-red-500 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center cart-count\">0</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- User Profile or Login/Register buttons -->\r\n");
      out.write("    ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("    <!-- User Dropdown Menu -->\r\n");
      out.write("    <div class=\"relative\" id=\"user-dropdown-container\">\r\n");
      out.write("      <button id=\"user-dropdown-btn\" class=\"flex items-center gap-2 py-2 px-3 rounded-full hover:bg-blue-200 transition-colors\">\r\n");
      out.write("        <div class=\"w-8 h-8 bg-green-500 rounded-full flex items-center justify-center text-white font-semibold\">\r\n");
      out.write("          ");
      out.print( headerUser.getUsername().substring(0, 1).toUpperCase() );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <span class=\"hidden md:block\">");
      out.print( headerUser.getUsername() );
      out.write("</span>\r\n");
      out.write("        <i class=\"fas fa-chevron-down text-xs\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <!-- Dropdown Menu -->\r\n");
      out.write("      <div id=\"user-dropdown\" class=\"absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-50 hidden\">\r\n");
      out.write("        <div class=\"px-4 py-2 border-b border-gray-100\">\r\n");
      out.write("          <p class=\"text-sm font-semibold\">");
      out.print( headerUser.getUsername() );
      out.write("</p>\r\n");
      out.write("          <p class=\"text-xs text-gray-500\">");
      out.print( headerUser.getEmail() );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"dashboard.jsp\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\r\n");
      out.write("          <i class=\"fas fa-user-circle mr-2\"></i> Dashboard\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        ");
 if ("admin".equals(headerUser.getRole())) { 
      out.write("\r\n");
      out.write("        <a href=\"admin/dashboard\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\r\n");
      out.write("          <i class=\"fas fa-shield-alt mr-2\"></i> Admin Panel\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/orderHistory\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\r\n");
      out.write("          <i class=\"fas fa-shopping-bag mr-2\"></i> My Orders\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"border-t border-gray-100 mt-1\"></div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"logout.jsp\" class=\"block px-4 py-2 text-sm text-red-600 hover:bg-gray-100\">\r\n");
      out.write("          <i class=\"fas fa-sign-out-alt mr-2\"></i> Logout\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("    <!-- Login/Register Buttons -->\r\n");
      out.write("    <div class=\"hidden md:flex gap-2\">\r\n");
      out.write("      <div class=\"relative\" id=\"login-dropdown-container\">\r\n");
      out.write("        <button id=\"login-dropdown-btn\" class=\"py-2 px-4 text-sm font-medium text-green-600 hover:text-green-800 transition-colors flex items-center\">\r\n");
      out.write("          Login <i class=\"fas fa-chevron-down ml-1 text-xs\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div id=\"login-dropdown\" class=\"absolute right-0 mt-1 w-48 bg-white rounded-md shadow-lg py-1 z-50 hidden\">\r\n");
      out.write("          <a href=\"login.jsp\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\r\n");
      out.write("            <i class=\"fas fa-user mr-2\"></i> User Login\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"admin-login.jsp\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\r\n");
      out.write("            <i class=\"fas fa-user-shield mr-2\"></i> Admin Login\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"register.jsp\" class=\"py-2 px-4 bg-green-600 text-white text-sm font-medium rounded-md hover:bg-green-700 transition-colors\">\r\n");
      out.write("        Register\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Login Button (only visible on small screens) -->\r\n");
      out.write("    <div class=\"md:hidden\">\r\n");
      out.write("      <button id=\"mobile-login-btn\" class=\"py-2 px-3 text-sm font-medium text-green-600 hover:text-green-800 transition-colors\">\r\n");
      out.write("        <i class=\"fas fa-user-circle text-xl\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div id=\"mobile-login-dropdown\" class=\"fixed inset-0 bg-black bg-opacity-50 z-50 hidden\">\r\n");
      out.write("        <div class=\"bg-white rounded-lg shadow-xl p-6 w-11/12 max-w-sm mx-auto mt-20\">\r\n");
      out.write("          <div class=\"flex justify-between items-center mb-4\">\r\n");
      out.write("            <h3 class=\"text-lg font-bold text-gray-800\">Login Options</h3>\r\n");
      out.write("            <button id=\"close-mobile-login\" class=\"text-gray-500 hover:text-gray-700\">\r\n");
      out.write("              <i class=\"fas fa-times\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"space-y-3\">\r\n");
      out.write("            <a href=\"login.jsp\" class=\"flex items-center justify-center gap-2 w-full py-3 px-4 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors\">\r\n");
      out.write("              <i class=\"fas fa-user mr-2\"></i> User Login\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"admin-login.jsp\" class=\"flex items-center justify-center gap-2 w-full py-3 px-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors\">\r\n");
      out.write("              <i class=\"fas fa-user-shield mr-2\"></i> Admin Login\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"border-t border-gray-200 my-2 pt-2 text-center\">\r\n");
      out.write("              <p class=\"text-sm text-gray-600 mb-2\">Don't have an account?</p>\r\n");
      out.write("              <a href=\"register.jsp\" class=\"flex items-center justify-center gap-2 w-full py-3 px-4 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 transition-colors\">\r\n");
      out.write("                <i class=\"fas fa-user-plus mr-2\"></i> Register\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Create logout.jsp functionality -->\r\n");
      out.write("<script>\r\n");
      out.write("  // User dropdown toggle\r\n");
      out.write("  document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    const userDropdownBtn = document.getElementById('user-dropdown-btn');\r\n");
      out.write("    const userDropdown = document.getElementById('user-dropdown');\r\n");
      out.write("\r\n");
      out.write("    if (userDropdownBtn) {\r\n");
      out.write("      userDropdownBtn.addEventListener('click', function(e) {\r\n");
      out.write("        e.stopPropagation();\r\n");
      out.write("        userDropdown.classList.toggle('hidden');\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Close dropdown when clicking outside\r\n");
      out.write("      document.addEventListener('click', function(e) {\r\n");
      out.write("        if (!document.getElementById('user-dropdown-container').contains(e.target)) {\r\n");
      out.write("          userDropdown.classList.add('hidden');\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Login dropdown toggle\r\n");
      out.write("    const loginDropdownBtn = document.getElementById('login-dropdown-btn');\r\n");
      out.write("    const loginDropdown = document.getElementById('login-dropdown');\r\n");
      out.write("\r\n");
      out.write("    if (loginDropdownBtn) {\r\n");
      out.write("      loginDropdownBtn.addEventListener('click', function(e) {\r\n");
      out.write("        e.stopPropagation();\r\n");
      out.write("        loginDropdown.classList.toggle('hidden');\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Close dropdown when clicking outside\r\n");
      out.write("      document.addEventListener('click', function(e) {\r\n");
      out.write("        if (!document.getElementById('login-dropdown-container').contains(e.target)) {\r\n");
      out.write("          loginDropdown.classList.add('hidden');\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Mobile login dropdown\r\n");
      out.write("    const mobileLoginBtn = document.getElementById('mobile-login-btn');\r\n");
      out.write("    const mobileLoginDropdown = document.getElementById('mobile-login-dropdown');\r\n");
      out.write("    const closeMobileLogin = document.getElementById('close-mobile-login');\r\n");
      out.write("\r\n");
      out.write("    if (mobileLoginBtn) {\r\n");
      out.write("      mobileLoginBtn.addEventListener('click', function() {\r\n");
      out.write("        mobileLoginDropdown.classList.remove('hidden');\r\n");
      out.write("        document.body.classList.add('overflow-hidden'); // Prevent scrolling\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      if (closeMobileLogin) {\r\n");
      out.write("        closeMobileLogin.addEventListener('click', function() {\r\n");
      out.write("          mobileLoginDropdown.classList.add('hidden');\r\n");
      out.write("          document.body.classList.remove('overflow-hidden');\r\n");
      out.write("        });\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // Close when clicking outside the modal content\r\n");
      out.write("      mobileLoginDropdown.addEventListener('click', function(e) {\r\n");
      out.write("        if (e.target === mobileLoginDropdown) {\r\n");
      out.write("          mobileLoginDropdown.classList.add('hidden');\r\n");
      out.write("          document.body.classList.remove('overflow-hidden');\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    // Function to update cart count\r\n");
      out.write("    function updateCartCount() {\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/count', {\r\n");
      out.write("            method: 'GET',\r\n");
      out.write("            headers: {\r\n");
      out.write("                'Accept': 'application/json',\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .then(response => response.json())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            const cartCountElements = document.querySelectorAll('.cart-count');\r\n");
      out.write("            cartCountElements.forEach(element => {\r\n");
      out.write("                element.textContent = data.count;\r\n");
      out.write("            });\r\n");
      out.write("        })\r\n");
      out.write("        .catch(error => {\r\n");
      out.write("            console.error('Error:', error);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Update cart count when page loads\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', updateCartCount);\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex flex-col items-center pt-[20%] gap-8\">\r\n");
      out.write("        <div class=\"flex flex-col gap-2 text-center cursor-text\">\r\n");
      out.write("            <h1 class=\"text-white text-5xl \">Your Health, Our Priority</h1>\r\n");
      out.write("            <p class=\"text-white text-2xl \">Buy genuine medicines at affordable prices</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <button class=\"bg-green-500 py-[5px] px-[10px] max-w-[150px] rounded-[5px] text-xl cursor-pointer hover:bg-green-600 hover:text-white hover:scale-110 transition-all duration-300\">\r\n");
      out.write("                <a href=\"#categories\" class=\"smooth-scroll\">SHOP NOW</a>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--second section Shop by Categories-->\r\n");
      out.write("<section class=\"gray-border\" id=\"categories\">\r\n");
      out.write("    <div class=\"flex flex-col my-[160px] items-center gap-[4rem] my-[3rem] mx-[2rem]\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <h1 class=\"text-4xl py-[5px] px-[8px] font-bold\"> Shop by Categories </h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--product categories-->\r\n");
      out.write("        <div>\r\n");
      out.write("            <ul class=\"flex flex-wrap gap-[2rem] md:gap-[5rem] py-[5px] px-[8px] justify-center text-center font-bold \">\r\n");
      out.write("                ");

                // Display each category with its own icon
                for (String category : categories) {
                    // Skip if no products in this category
                    if (productsByCategory.get(category) == null || productsByCategory.get(category).isEmpty())
                        continue;

                    // Create a category ID for anchor links
                    String categoryId = category.replaceAll("\\s+", "");

                    // Choose an appropriate icon based on category
                    String iconImage = "miscellaneousItems.jpg"; // default
                    if (category.contains("Medicine")) {
                        iconImage = "CProduct1.jpg";
                    } else if (category.contains("Equipment")) {
                        iconImage = "healthitems.jpg";
                    } else if (category.contains("Wellness")) {
                        iconImage = "CProduct2.webp";
                    } else if (category.contains("Personal")) {
                        iconImage = "CProduct3.jpeg";
                    }
                
      out.write("\r\n");
      out.write("                <li class=\"product-categories-items-li\" >\r\n");
      out.write("                    <a href=\"#");
      out.print( categoryId );
      out.write("\" class=\"flex flex-col gap-5 smooth-scroll\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/");
      out.print( iconImage );
      out.write("\" class=\"w-[170px] h-[150px] object-contain\"  >\r\n");
      out.write("                        <h3 class=\"max-w-40\">");
      out.print( category );
      out.write("</h3>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- third section-->\r\n");
      out.write("<section class=\"gray-border \">\r\n");
      out.write("    <div class=\"section-main-div\">\r\n");
      out.write("        <!--product container title-->\r\n");
      out.write("        <div class=\"product-container-title-div\">\r\n");
      out.write("            <h3 class=\"product-container-title\">\r\n");
      out.write("                Featured Products\r\n");
      out.write("            </h3>\r\n");
      out.write("            <div class=\"w-30 h-1.5 bg-green-500 mx-auto rounded-full\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--product container-->\r\n");
      out.write("        <div class=\"product-container\">\r\n");
      out.write("            ");

            // Display featured products
            for (Product product : featuredProducts) {
                String imagePath = product.getImagePath() != null && !product.getImagePath().isEmpty()
                                  ? product.getImagePath()
                                  : "resources/images/CProduct1.jpg";
            
      out.write("\r\n");
      out.write("            <div class=\"product-main\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.print( imagePath );
      out.write("\"\r\n");
      out.write("                     alt=\"");
      out.print( product.getName() );
      out.write("\" class=\"product-image\" >\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <h4 class=\"product-title\">");
      out.print( product.getName() );
      out.write("</h4>\r\n");
      out.write("                    <p class=\"product-price\">$");
      out.print( String.format("%.2f", product.getPrice()) );
      out.write("</p>\r\n");
      out.write("                    <button class=\"product-button add-to-cart\"\r\n");
      out.write("                            data-id=\"");
      out.print( product.getProductId() );
      out.write("\"\r\n");
      out.write("                            data-name=\"");
      out.print( product.getName() );
      out.write("\"\r\n");
      out.write("                            data-price=\"");
      out.print( product.getPrice() );
      out.write("\"\r\n");
      out.write("                            data-image=\"");
      out.print( imagePath );
      out.write("\">\r\n");
      out.write("                        <i class=\"fas fa-cart-plus mr-2\"></i> Add to Cart\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (featuredProducts.isEmpty()) { 
      out.write("\r\n");
      out.write("            <!-- Display default products if no products exist -->\r\n");
      out.write("            <div class=\"product-main\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/CProduct1.jpg\" alt=\"Hand Sanitizer\" class=\"product-image\" >\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <h4 class=\"product-title\">Hand Sanitizer</h4>\r\n");
      out.write("                    <p class=\"product-price\">$8.99</p>\r\n");
      out.write("                    <button class=\"product-button add-to-cart\" data-id=\"1\" data-name=\"Hand Sanitizer\" data-price=\"8.99\" data-image=\"CProduct1.jpg\">\r\n");
      out.write("                        <i class=\"fas fa-cart-plus mr-2\"></i> Add to Cart\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Add more default products as needed -->\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Dynamic category sections -->\r\n");

// For each category, create a section
for (String category : categories) {
    List<Product> categoryProducts = productsByCategory.get(category);

    // Skip if no products in this category
    if (categoryProducts == null || categoryProducts.isEmpty()) continue;

    // Create a category ID for anchor links
    String categoryId = category.replaceAll("\\s+", "");

      out.write("\r\n");
      out.write("<section class=\"gray-border\" id=\"");
      out.print( categoryId );
      out.write("\">\r\n");
      out.write("    <div class=\"section-main-div\">\r\n");
      out.write("        <!--product container title-->\r\n");
      out.write("        <div class=\"product-container-title-div\">\r\n");
      out.write("            <h3 class=\"product-container-title\">\r\n");
      out.write("                ");
      out.print( category );
      out.write("\r\n");
      out.write("            </h3>\r\n");
      out.write("            <div class=\"w-30 h-1.5 bg-green-500 mx-auto rounded-full\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--product container-->\r\n");
      out.write("        <div class=\"product-container-main-div\">\r\n");
      out.write("            <div class=\"product-container\">\r\n");
      out.write("                ");

                for (Product product : categoryProducts) {
                    String imagePath = product.getImagePath() != null && !product.getImagePath().isEmpty()
                                      ? product.getImagePath()
                                      : "resources/images/CProduct1.jpg";
                
      out.write("\r\n");
      out.write("                <div class=\"product-main\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.print( imagePath );
      out.write("\"\r\n");
      out.write("                         alt=\"");
      out.print( product.getName() );
      out.write("\" class=\"product-image\" >\r\n");
      out.write("                    <div class=\"p-4\">\r\n");
      out.write("                        <h4 class=\"product-title\">");
      out.print( product.getName() );
      out.write("</h4>\r\n");
      out.write("                        <p class=\"product-price\">$");
      out.print( String.format("%.2f", product.getPrice()) );
      out.write("</p>\r\n");
      out.write("                        <button class=\"product-button add-to-cart\"\r\n");
      out.write("                                data-id=\"");
      out.print( product.getProductId() );
      out.write("\"\r\n");
      out.write("                                data-name=\"");
      out.print( product.getName() );
      out.write("\"\r\n");
      out.write("                                data-price=\"");
      out.print( product.getPrice() );
      out.write("\"\r\n");
      out.write("                                data-image=\"");
      out.print( imagePath );
      out.write("\">\r\n");
      out.write("                            <i class=\"fas fa-cart-plus mr-2\"></i> Add to Cart\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- About Section -->\r\n");
      out.write("<section class=\"py-10 h-[800px]  bg-gradient-to-br from-blue-50 to-green-50 gray-border \" id=\"about\">\r\n");
      out.write("    <div class=\"container mx-auto px-4 max-w-6xl pt-[80px]\">\r\n");
      out.write("        <!-- Header -->\r\n");
      out.write("        <div class=\"text-center mb-12\">\r\n");
      out.write("            <h2 class=\"text-4xl font-bold text-gray-800 mb-4\">About MediCare Center</h2>\r\n");
      out.write("            <div class=\"w-30 h-1.5 bg-green-500 mx-auto rounded-full\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Content Box -->\r\n");
      out.write("        <div class=\"bg-white rounded-xl shadow-lg overflow-hidden\">\r\n");
      out.write("            <div class=\"md:flex\">\r\n");
      out.write("                <!-- Image Side -->\r\n");
      out.write("                <div class=\"md:w-1/2\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/about.jpeg\"\r\n");
      out.write("                         alt=\"Our Medical Center\"\r\n");
      out.write("                         class=\"w-full h-full object-cover\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Text Side -->\r\n");
      out.write("                <div class=\"md:w-1/2 p-8 md:p-10\">\r\n");
      out.write("                    <h3 class=\"text-2xl font-semibold text-gray-800 mb-4\">Your Trusted Online Healthcare Partner</h3>\r\n");
      out.write("                    <p class=\"text-gray-600 mb-6 leading-relaxed\">\r\n");
      out.write("                        At MediCare Center, we're revolutionizing healthcare access by bringing quality medical\r\n");
      out.write("                        products and services directly to your doorstep. Our platform connects you with genuine\r\n");
      out.write("                        medicines, health essentials, and professional advice - all from the comfort of your home.\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"space-y-4\">\r\n");
      out.write("                        <div class=\"flex place-items-start \">\r\n");
      out.write("                            <div class=\"flex-shrink-0 mt-1 text-green-500\">\r\n");
      out.write("                                <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ml-3 text-gray-600\">100% authentic pharmaceutical products</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"flex items-start\">\r\n");
      out.write("                            <div class=\"flex-shrink-0 mt-1 text-green-500\">\r\n");
      out.write("                                <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ml-3 text-gray-600\">Verified doctors and pharmacists on call</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"flex items-start\">\r\n");
      out.write("                            <div class=\"flex-shrink-0 mt-1 text-green-500\">\r\n");
      out.write("                                <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ml-3 text-gray-600\">Fast, discreet delivery nationwide</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"#\" class=\"inline-block mt-8 bg-green-500 hover:bg-green-600 text-white font-medium py-3 px-8 rounded-full transition duration-300 shadow-md hover:shadow-lg\">\r\n");
      out.write("                        Discover Our Story\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- footer section-->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"gray-border bg-green-500 my-gradiant flex flex-col py-5 \">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex justify-between gap-8 w-full max-w-7xl mx-auto px-4 my-6 sm:px-6 md:px-8 text-white \">\r\n");
      out.write("        <div class=\"flex flex-col gap-5 w-full max-w-80\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <a href=\"index.jsp\" class=\"text-[#ffff] text-3xl bg-green-700 py-[10px] px-[15px] rounded-full\">MEDICARE CENTER</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex flex-col gap-4\">\r\n");
      out.write("                <p class=\"leading-relaxed justify-center\">\r\n");
      out.write("                    Medicare Pharmacy is a licensed and registered pharmacy compliant with NMRA (National Medicine Regulatory Authority). Registration No: (NMRA/R/5255/2022)\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>medicare.lk is the online store owned and managed by CareLink Pharmacy.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"flex gap-2 text-xl\">\r\n");
      out.write("                <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("                <i class=\"fa-brands fa-whatsapp\"></i>\r\n");
      out.write("                <i class=\"fa-brands fa-linkedin\"></i>\r\n");
      out.write("                <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"flex flex-col gap-8 \">\r\n");
      out.write("            <div class=\"font-semibold \">\r\n");
      out.write("                <h4>Corporate</h4>\r\n");
      out.write("                <div class=\"w-18 h-1 bg-white rounded-full\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex flex-col leading-relaxed \">\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">About Us</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Careers</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Advertise with us</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Contact Us</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Knowledge Base</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"flex flex-col gap-8\">\r\n");
      out.write("            <div class=\"font-semibold \">\r\n");
      out.write("                <h4>Help</h4>\r\n");
      out.write("                <div class=\"w-9 h-1 bg-white rounded-full\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex flex-col leading-relaxed \">\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">My account</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">FAQ</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Contact Us</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Returns & Refund Policy</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Delivery Policy</a>\r\n");
      out.write("                <a href=\"#\" class=\"hover:text-black\">Sitemap</a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"flex flex-col gap-8\">\r\n");
      out.write("            <div class=\"font-semibold \">\r\n");
      out.write("                <h4>Contact Store</h4>\r\n");
      out.write("                <div class=\"w-26 h-1 bg-white rounded-full\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"leading-relaxed judtify-center\" >\r\n");
      out.write("                <div class=\"flex place-items-start gap-2 \">\r\n");
      out.write("                    <div class=\"flex-shrink-0 mt-1 text-white-500\">\r\n");
      out.write("                        <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"hover:text-black\">No: 266, colombo Road, kaduwela, Sri Lanka 11010</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex place-items-start gap-2  \">\r\n");
      out.write("                    <div class=\"flex-shrink-0 mt-1 text-white-500\">\r\n");
      out.write("                        <i class=\"fa-solid fa-phone\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"hover:text-black\">011 858 6639</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex place-items-start gap-2 \">\r\n");
      out.write("                    <div class=\"flex-shrink-0 mt-1 text-white-500\">\r\n");
      out.write("                        <i class=\"fa-solid fa-phone\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"hover:text-black\">+94 77 788 3979</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex place-items-start gap-2 \">\r\n");
      out.write("                    <div class=\"flex-shrink-0 mt-1 text-white-500\">\r\n");
      out.write("                        <i class=\"fa-solid fa-square-envelope\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"hover:text-black\">info@medicare.lk</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\" flex flex-col w-full max-w-md mx-auto flex items-center justify-center gap-3\">\r\n");
      out.write("        <h3 class=\"text-center text-white text-xl\">Secured payment with</h3>\r\n");
      out.write("        <div>\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/payment.webp\" alt=\"payment\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript for cart functionality -->\r\n");
      out.write("<!-- Replace the JavaScript for cart functionality in index.jsp with this: -->\r\n");
      out.write("<script>\r\n");
      out.write("    // Add to cart functionality\r\n");
      out.write("    document.querySelectorAll('.add-to-cart').forEach(button => {\r\n");
      out.write("        button.addEventListener('click', function() {\r\n");
      out.write("            const productId = this.getAttribute('data-id');\r\n");
      out.write("            const productName = this.getAttribute('data-name');\r\n");
      out.write("\r\n");
      out.write("            // Send AJAX request to add item to cart\r\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: {\r\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("                },\r\n");
      out.write("                body: `action=add&productId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`\r\n");
      out.write("            })\r\n");
      out.write("                .then(response => response.json())\r\n");
      out.write("                .then(data => {\r\n");
      out.write("                    if (data.success) {\r\n");
      out.write("                        // Update cart count in header\r\n");
      out.write("                        const cartCountElements = document.querySelectorAll('.cart-count');\r\n");
      out.write("                        cartCountElements.forEach(element => {\r\n");
      out.write("                            element.textContent = data.cartSize;\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                        // Show toast notification\r\n");
      out.write("                        showToast(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" added to cart!`);\r\n");
      out.write("\r\n");
      out.write("                        // Add animation to button\r\n");
      out.write("                        this.classList.add('bg-green-700');\r\n");
      out.write("                        setTimeout(() => {\r\n");
      out.write("                            this.classList.remove('bg-green-700');\r\n");
      out.write("                        }, 300);\r\n");
      out.write("                    }\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => {\r\n");
      out.write("                    console.error('Error:', error);\r\n");
      out.write("                });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Show toast notification\r\n");
      out.write("    function showToast(message) {\r\n");
      out.write("        const toast = document.getElementById('toast');\r\n");
      out.write("        const toastMessage = document.getElementById('toast-message');\r\n");
      out.write("\r\n");
      out.write("        toastMessage.textContent = message;\r\n");
      out.write("        toast.classList.add('toast-show');\r\n");
      out.write("\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            toast.classList.remove('toast-show');\r\n");
      out.write("        }, 3000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Smooth scrolling for anchor links\r\n");
      out.write("    document.querySelectorAll('.smooth-scroll').forEach(anchor => {\r\n");
      out.write("        anchor.addEventListener('click', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            const targetId = this.getAttribute('href');\r\n");
      out.write("            const targetElement = document.querySelector(targetId);\r\n");
      out.write("\r\n");
      out.write("            if (targetElement) {\r\n");
      out.write("                // Remove highlight from all sections\r\n");
      out.write("                document.querySelectorAll('section').forEach(section => {\r\n");
      out.write("                    section.classList.remove('section-highlight');\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Scroll to the target section\r\n");
      out.write("                window.scrollTo({\r\n");
      out.write("                    top: targetElement.offsetTop - 100,\r\n");
      out.write("                    behavior: 'smooth'\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Add highlight effect to the target section\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    targetElement.classList.add('section-highlight');\r\n");
      out.write("\r\n");
      out.write("                    // Remove highlight after animation\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        targetElement.classList.remove('section-highlight');\r\n");
      out.write("                    }, 1500);\r\n");
      out.write("                }, 500);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Update cart count on page load\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        updateCartCount();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
